x = input('\033[1;34mDigite algo:\033[m ')
print('O tipo primitivo desse valor é ', type(x))
print('Só tem espaço: ', x.isspace())
print('É um número: ', x.isnumeric())
print('É alfabético: ', x.isalpha())
print('É alfanumérico: ', x.isalnum())
print('Está em maiúsculas: ', x.isupper())
print('Está em minúsculas: ', x.islower())
print('Está capitalizada: ', x.istitle())
